In [1]:
import gym
import numpy as np 
import tensorflow as tf

In [2]:
tensor = tf.constant([[1,2],[3,4]])

In [3]:
print("Tensor:")
print(tensor)

Tensor:
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
variable = tf.Variable(tf.zeros([2,2]))

In [6]:
print("\nvariable:")
print(variable)


variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>


In [7]:
variable.assign_add(tf.ones([2,2]))

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [8]:
print("\nUpdated Variable:")
print(variable)


Updated Variable:
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>


In [9]:
env = gym.make("CartPole-v1")

In [10]:
state = env.reset()

In [11]:
for _ in range(100):
    env.render()

/Users/vedantkamajdar/anaconda3/lib/python3.10/site-packages/gym/envs/classic_control/cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  gym.logger.warn(


In [12]:
action = env.action_space.sample()

In [13]:
result = env.step(action)

In [14]:
next_state, reward, done, info = result[:4]

In [15]:
if done:
    state = env.reset()

env.close()